name: Deploy Rook Staging

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Render CLI
        run: |
          curl -L https://github.com/render-oss/cli/releases/download/v1.1.0/cli_1.1.0_linux_amd64.zip -o render.zip

          unzip -o render.zip

          sudo mv cli_v1.1.0 /usr/local/bin/render
          sudo chmod +x /usr/local/bin/render

      - name: Deploy Staging
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_STAGING_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.API_KEY_RENDER }}
          CI: true
        run: |
          render deploys create $RENDER_SERVICE_ID \
            --output json \
            --confirm \
            --wait